### ISSUE TITLE
templates: create example for MARC21

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-records-ui#26]
Create basic templates for MARC21 compatible records in `examples/templates/invenio_marc21/detail.html` that can be later moved to new `invenio-marc21` package.

**Comment by switowski** [comment]
Create the templates directly in invenio-marc21 package

**Comment by switowski** [comment]
Reuse CDS labs templates (for brief and detailed views)

**Comment by hachreak** [comment]
https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/templates/invenio_records_ui/detail.html

**Comment by switowski** [comment]
Closed with https://github.com/inveniosoftware/invenio-marc21/pull/8
