### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records-ui#47]
- [ ] check existing API functionality
- [ ] add missing important API functionality
- [ ] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by hachreak** [comment]
@jirikuncar @lnielsen do you think the first 3 points are fine? Or do we need to improve somehow the API?

**Comment by hachreak** [comment]
ping @lnielsen @jirikuncar 
I think, if there is no new PRs and/or Issues, we can close it. WDYT?
