### ISSUE TITLE
docs: update structure

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records-ui#48]
- [ ] introduce new documentation structure https://github.com/inveniosoftware/cookiecutter-invenio-module/issues/56
- [ ] document user perspective
- [ ] document signals (if not done)
- [ ] document example app (if not done)

**Comment by hachreak** [comment]
@jirikuncar I think we can close this issue, WDYT?

**Comment by jirikuncar** [comment]
@hachreak no we can close only #47.

**Comment by hachreak** [comment]
@jirikuncar could you check what we can consider done? Just to know what is still pending.
