### ISSUE TITLE
config: move configuration from ext.py to config.py

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-records-ui#49]
Can we move the configuration inside a configuration file as is done in `invenio-records-rest`?
This can help to write the documentation.

**Comment by lnielsen** [comment]
Do you mean moving [this](https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/ext.py#L81-L101) from ``ext.py`` into a ``config.py``?

**Comment by hachreak** [comment]
I was thinking only `RECORDS_UI_ENDPOINTS`, but yes, maybe It's a good idea to move all the configuration inside config.py.

**Comment by lnielsen** [comment]
Fine be my - i've update the issue title.
