### ISSUE TITLE
views/ext: template context processors

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-ui#5]
It should be possible to add template context processors to the records view in a similar way like flask-security, so that pages such as references/usage statistics etc can ingest custom variables into the template.

**Comment by jirikuncar** [comment]
@lnielsen do you have any example? Shall we include it in Sprint-Record-Data-Model?

**Comment by lnielsen** [comment]
So far it hasn't been necessary, and you can achieve a lot with just template filters so I wouldn't tackle it now until we have a real use case.
