### ISSUE TITLE
templates: common template macros

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-ui#6]
We should add a helper library of template macros that can be used to make formatting record pages easier (e.g. adding et.al. to list of authors).

**Comment by jirikuncar** [comment]
`invenio-formatter`?

**Comment by lnielsen** [comment]
Weren't we going to kill ``invenio-formatter``? or you propose that we make a new module with all these extra jinja2 goodies?

**Comment by jirikuncar** [comment]
`invenio-formatter` can contain only Jinja2 goodies such as macros, filters, etc. that can be used not only for formatting records but as a base for any theme package.

**Comment by lnielsen** [comment]
Sounds good to me - i.e. this ticket can be closed once we bootstrap the new module.

**Comment by tiborsimko** [comment]
Closing as per the release of `invenio-formatter` v1.0.0a.  The common formatting goodies can be further discussed there.
