### ISSUE TITLE
Add search and edit UI endpoints

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-records-ui#69]
It would be great to make `invenio-records-ui` the complete UI version of `invenio-records-rest`. For the `REST` version, it is possible to list the records given a query and filters and to create, edit, delete a record. It would be great to have configuration entries in `RECORDS_UI_ENDPOINTS ` to specify a `search` endpoint and a simple editor endpoint such as: `/records/new`, `/records/1234/edit`, `/records/search`, etc. 

This can be super useful especially when the records are not limited to bibliographic records, such as library localisation for the `invenio-circulation` module.

**Comment by lnielsen** [comment]
Invenio-Search-UI provides the query and filtering part. The edit part quickly gets pretty complex so I prefer to keep it in a separate module. That said, it would be useful to have something which is not Invenio-Deposit.

**Comment by lnielsen** [comment]
Closing this issue as we're not realisticly going to do this anytime soon.
