### ISSUE TITLE
global: load blueprints via "invenio_base.blueprints"

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-records-ui#81]
Based on the changes introduced in inveniosoftware/invenio-base#133, it will be possible to load blueprints via a function, allowing for the application to have loaded any `RECORDS_UI_ENDPOINTS` config from other extensions before creating and registering the [`invenio_records_ui` blueprint](https://github.com/inveniosoftware/invenio-records-ui/blob/c48fe8c199dc9defc192ae27247cd61731530a5c/invenio_records_ui/ext.py#L73-L74). This allows for flexible "feature-flags" as described in inveniosoftware/cookiecutter-invenio-datamodel#18.

*Note: https://github.com/inveniosoftware/invenio-records-rest/pull/210 implements this for `invenio-records-rest`)*

**Comment by lnielsen** [comment]
Isn't this one needed for the cookeicutter instances? i.e. I think we should have a record detail view
